services:
  - type: web
    name: teamsync
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: teamsync-db
          property: connectionString

databases:
  - name: teamsync-db
    databaseName: teamsync
    user: teamsync
